# Generated by Django 5.2.7 on 2026-02-14 15:27

import apps.fields.autoslugfield
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=5, null=True)),
                ('code', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', apps.fields.autoslugfield.AutoSlugField(blank=True, editable=False, populate_from=('id', 'code', 'name'))),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('date_built', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.country')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.team')),
            ],
        ),
    ]
