# Generated by Django 5.2.7 on 2026-02-14 15:27

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('leagues', '0001_initial'),
        ('match', '0002_initial'),
        ('persons', '0001_initial'),
        ('polls', '0001_initial'),
        ('region', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=220)),
                ('subtitle', models.CharField(blank=True, max_length=120, null=True)),
                ('structure', models.CharField(choices=[('STANDALONE', 'Stand-alone Post/Podcast'), ('PARENT', 'Parent Post/Podcast'), ('CHILD', 'Child Post/Podcast Season')], default='STANDALONE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField()),
                ('competitions', models.ManyToManyField(blank=True, to='leagues.league')),
                ('countries', models.ManyToManyField(blank=True, to='region.country')),
                ('matches', models.ManyToManyField(blank=True, to='match.match')),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent only if this is a Season or Child post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='posts.post')),
                ('players', models.ManyToManyField(blank=True, to='persons.player')),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('regions', models.ManyToManyField(blank=True, to='region.region')),
                ('subscribers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, to='clubs.team')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('analytics', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('funny', 'Funny'), ('dislike', 'Dislike')], default='like', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
