# Generated by Django 5.2.7 on 2026-02-14 15:27

import apps.posts.polls.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=120, null=True)),
                ('structure', models.CharField(choices=[('STANDALONE', 'Stand-alone Post/Podcast'), ('PARENT', 'Parent Post/Podcast'), ('CHILD', 'Child Post/Podcast Season')], default='STANDALONE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220, verbose_name='Question')),
                ('max_hours', models.FloatField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent only if this is a Season or Child post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='polls.poll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.posts.polls.models.poll_upload_to)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('votes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.poll')),
            ],
        ),
    ]
