# Generated by Django 5.2.7 on 2026-02-14 15:27

import apps.thumbnail.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('xl', 'XL'), ('lg', 'LG'), ('md', 'MD'), ('sm', 'SM'), ('xs', 'XS')], default='md', max_length=2)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('media', models.ImageField(blank=True, height_field='height', null=True, upload_to=apps.thumbnail.models.thumbnail_upload_to, width_field='width')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
