# Generated by Django 5.2.7 on 2026-02-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='memberships.entitlement', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='billing.sourcetype', verbose_name='Source Type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.source', verbose_name='Source'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source', 'status'], name='billing_tra_source__f7ded8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference', 'amount'], name='billing_tra_referen_ea57c6_idx'),
        ),
    ]
