# Generated by Django 5.2.7 on 2026-02-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('match', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('5-4-1', '5-4-1'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3'), ('4-2-4', '4-2-4'), ('4-3-1-2', '4-3-1-2')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Goal Keeper'), ('SWK', 'Sweeper Keeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('CBC', 'Center Back'), ('CBR', 'Right Center Back'), ('CBL', 'Left Center Back'), ('DMF', 'Defensive MidFielder'), ('CMF', 'Central MidFielder'), ('CMR', 'Right Central MidFielder'), ('CML', 'Left Central MidFielder'), ('CAM', 'Central Attacking MidFielder'), ('LM', 'Left MidFielder'), ('RM', 'Right MidFielder'), ('RWF', 'Right Wing Forward'), ('LWF', 'Left Wing Forward'), ('SS', 'Supporting/Shadow Striker'), ('ST', 'Striker'), ('RST', 'Right Striker'), ('LST', 'Left Striker'), ('CF', 'Center Forward')], max_length=4)),
                ('top', models.PositiveIntegerField(default=0)),
                ('left', models.PositiveIntegerField(default=0)),
                ('bottom', models.PositiveIntegerField(default=0)),
                ('right', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_played', to='persons.player')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='tactics.position')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='tactics.formationstyle')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='tactics.shape'),
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup', models.ManyToManyField(blank=True, to='tactics.lineup')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='tactics.shape')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLineUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactics.formation')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.staff')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='clubs.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchLineUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='match.match')),
                ('away_lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_lineups', to='tactics.teamlineup')),
                ('home_lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_lineups', to='tactics.teamlineup')),
            ],
        ),
    ]
