# Generated by Django 5.2.7 on 2026-02-14 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Object View',
                'verbose_name_plural': 'Object Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'content_type'], name='analytics_o_user_id_b54e33_idx'), models.Index(fields=['content_type', 'object_id', 'ip_address', 'timestamp'], name='analytics_o_content_ad4cf6_idx')],
            },
        ),
    ]
