# Generated by Django 5.2.7 on 2026-02-14 15:27

import apps.media.audio.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='seconds', null=True)),
                ('codec', models.CharField(default='mp3', max_length=32)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('quality', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('hls', 'HLS'), ('preview', 'Preview')], help_text='Quality to save or Preset key used to generate HLS (low|medium|high)', max_length=16, null=True)),
                ('file', models.FileField(upload_to=apps.media.audio.models.audio_upload_to)),
                ('prefix', models.CharField(blank=True, help_text='Storage prefix for HLS segments (directory or key prefix)', max_length=512)),
                ('bitrate', models.PositiveIntegerField(blank=True, help_text='kbps', null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.BooleanField(default=False)),
            ],
        ),
    ]
