# Generated by Django 5.2.7 on 2026-02-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0001_initial'),
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='podcasts.episode'),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=models.Index(fields=['episode', 'quality'], name='audio_audio_episode_a0113f_idx'),
        ),
        migrations.AddConstraint(
            model_name='audio',
            constraint=models.UniqueConstraint(condition=models.Q(('master', True)), fields=('episode',), name='unique_master_per_episode'),
        ),
        migrations.AddConstraint(
            model_name='audio',
            constraint=models.UniqueConstraint(fields=('episode', 'quality'), name='unique_episode_quality'),
        ),
    ]
