# Generated by Django 5.2.7 on 2026-02-14 15:27

import apps.fields.autoslugfield
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('slug', apps.fields.autoslugfield.AutoSlugField(blank=True, editable=False, populate_from=('name', 'id', 'tier'), unique=True)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-weight', 'name'],
            },
        ),
    ]
