# Generated by Django 5.2.7 on 2026-02-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.plan'),
        ),
    ]
