# Generated by Django 5.2.7 on 2026-02-14 15:27

import apps.fields.autoslugfield
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', apps.fields.autoslugfield.AutoSlugField(blank=True, editable=False, populate_from=('id', 'name', 'code'))),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', apps.fields.autoslugfield.AutoSlugField(blank=True, editable=False, populate_from=('id', 'name', 'code'))),
                ('code', models.IntegerField(blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='region.region')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
