# Generated by Django 5.2.7 on 2026-02-14 15:27

import apps.fields.tagsfield
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('clubs', '0001_initial'),
        ('leagues', '0001_initial'),
        ('match', '0001_initial'),
        ('persons', '0001_initial'),
        ('region', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=220)),
                ('subtitle', models.CharField(blank=True, max_length=120, null=True)),
                ('structure', models.CharField(choices=[('STANDALONE', 'Stand-alone Post/Podcast'), ('PARENT', 'Parent Post/Podcast'), ('CHILD', 'Child Post/Podcast Season')], default='STANDALONE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', apps.fields.tagsfield.TagsField(blank=True, max_length=255, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='podcasts', to='category.category')),
                ('competitions', models.ManyToManyField(blank=True, to='leagues.league')),
                ('countries', models.ManyToManyField(blank=True, to='region.country')),
                ('matches', models.ManyToManyField(blank=True, to='match.match')),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent only if this is a Season or Child post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='podcasts.podcast')),
                ('players', models.ManyToManyField(blank=True, to='persons.player')),
                ('regions', models.ManyToManyField(blank=True, to='region.region')),
                ('subscribers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, to='clubs.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=220, null=True)),
                ('slug', models.UUIDField(default=uuid.uuid4)),
                ('hosts', apps.fields.tagsfield.TagsField(blank=True, max_length=220, null=True)),
                ('tags', apps.fields.tagsfield.TagsField(blank=True, max_length=255, null=True)),
                ('public_release_date', models.DateTimeField(blank=True, null=True)),
                ('exclusive', models.BooleanField(default=False, help_text='If True, only paying plans (Fan+) can access after release')),
                ('early_access_hours', models.PositiveSmallIntegerField(blank=True, help_text='If set overrides plan early access hours', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trend_score', models.FloatField(db_index=True, default=0.0)),
                ('categories', models.ManyToManyField(blank=True, related_name='episodes', to='category.category')),
                ('competitions', models.ManyToManyField(blank=True, to='leagues.league')),
                ('countries', models.ManyToManyField(blank=True, to='region.country')),
                ('matches', models.ManyToManyField(blank=True, to='match.match')),
                ('players', models.ManyToManyField(blank=True, to='persons.player')),
                ('regions', models.ManyToManyField(blank=True, to='region.region')),
                ('subscribers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, to='clubs.team')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcast')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ('-public_release_date',),
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('model', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='podcasts.episode')),
            ],
        ),
        migrations.CreateModel(
            name='PlayBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('current_timestamp', models.IntegerField(default=0, help_text='Seconds Played')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.episode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PlayBack',
                'ordering': ['-last_played_at'],
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
