# Generated by Django 5.2.7 on 2026-02-14 15:27

import apps.fields.autoslugfield
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('code', apps.fields.autoslugfield.AutoSlugField(blank=True, editable=False, populate_from=('start', 'end'))),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', apps.fields.autoslugfield.AutoSlugField(blank=True, editable=False, populate_from=('id', 'name', 'region', 'timestamp'))),
                ('code', models.IntegerField(blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to='region.country')),
            ],
        ),
    ]
