# Generated by Django 5.2.7 on 2026-02-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('persons', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.video')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            bases=('video.video',),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1, verbose_name='Match Day')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SetPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('corner_kick', 'Corner Kick'), ('free_kick', 'Free Kick')], max_length=120)),
                ('minute', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on_target', models.BooleanField(default=False)),
                ('minute', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(choices=[('injury', 'Injury'), ('tactical', 'Tactical')], default='tactical', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPossession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red')], default='yellow', max_length=10)),
                ('is_straight_red', models.BooleanField(default=False)),
                ('is_second_yellow', models.BooleanField(default=False)),
                ('minute', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='persons.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clubs.team')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookings', models.ManyToManyField(blank=True, to='match.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Foul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.TimeField(auto_now_add=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.team')),
            ],
        ),
        migrations.CreateModel(
            name='FoulEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.event')),
                ('foul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.foul')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='fouls',
            field=models.ManyToManyField(blank=True, through='match.FoulEvent', through_fields=('event', 'foul'), to='match.foul'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.TimeField(auto_now_add=True)),
                ('is_own_goal', models.BooleanField(default=False)),
                ('assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='persons.player')),
            ],
        ),
    ]
