# Generated by Django 5.2.7 on 2026-02-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('leagues', '0001_initial'),
        ('match', '0001_initial'),
        ('persons', '0001_initial'),
        ('tactics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assist_experimental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists_experimental', to='tactics.lineup'),
        ),
        migrations.AddField(
            model_name='goal',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='persons.player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='scorer_experimental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_experimental', to='tactics.lineup'),
        ),
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.team'),
        ),
        migrations.AddField(
            model_name='goalevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.event'),
        ),
        migrations.AddField(
            model_name='goalevent',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.goal'),
        ),
        migrations.AddField(
            model_name='event',
            name='goals',
            field=models.ManyToManyField(blank=True, through='match.GoalEvent', through_fields=('event', 'goal'), to='match.goal'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='clubs.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.campaign'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='leagues.league'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='clubs.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.stadium'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='match.match'),
        ),
        migrations.AddField(
            model_name='event',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.match'),
        ),
        migrations.AddField(
            model_name='event',
            name='possession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.possession'),
        ),
        migrations.AddField(
            model_name='setpiece',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='set_piece',
            field=models.ManyToManyField(blank=True, to='match.setpiece'),
        ),
        migrations.AddField(
            model_name='shot',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='persons.player'),
        ),
        migrations.AddField(
            model_name='shot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='shots',
            field=models.ManyToManyField(blank=True, to='match.shot'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='player_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_ins', to='persons.player'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='player_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_outs', to='persons.player'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='clubs.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='substitutions',
            field=models.ManyToManyField(blank=True, to='match.substitution'),
        ),
        migrations.AddField(
            model_name='teampossession',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_possession', to='clubs.team'),
        ),
        migrations.AddField(
            model_name='possession',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_possession', to='match.teampossession'),
        ),
        migrations.AddField(
            model_name='possession',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_possession', to='match.teampossession'),
        ),
    ]
